# Google Analytics Tracking ID
google_analytics: UA-143239688-1

# Default portfolio post
default_cover_image: /images/unsplash.jpg
default_post_title: Portfolio Item

# Sidebar
sidebar: right
widgets:
- recent_posts
- archive